<?php
declare(strict_types=1);
require_once __DIR__ . '/access.php';
require_role('employee');
require_permission('apply_leave');
require_once __DIR__ . '/activity.php';
require_once __DIR__ . '/employee_ui.php';
$message = null; $error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); try { $from = (string) ($_POST['from_date'] ?? ''); $to = (string) ($_POST['to_date'] ?? ''); $reason = trim((string) ($_POST['reason'] ?? '')); if (!$from || !$to || !$reason || $from > $to) { throw new RuntimeException('Enter valid dates and a reason.'); } db()->prepare('INSERT INTO leave_requests (employee_id, from_date, to_date, reason) VALUES (?, ?, ?, ?)')->execute([$_SESSION['user']['id'], $from, $to, $reason]); log_activity((int) $_SESSION['user']['id'], 'Applied for leave', 'other'); $message = 'Leave request submitted.'; } catch (Throwable $e) { $error = $e->getMessage(); } }
$stmt = db()->prepare('SELECT from_date, to_date, reason, status, created_at FROM leave_requests WHERE employee_id = ? ORDER BY created_at DESC'); $stmt->execute([$_SESSION['user']['id']]); $requests = $stmt->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Apply Leave</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-4" style="max-width:800px"><div class="d-flex justify-content-between"><h1 class="h3">Leave Requests</h1><a href="employee_dashboard.php">Dashboard</a></div><?php if ($message): ?><div class="alert alert-success"><?= e($message) ?></div><?php endif; ?><?php if ($error): ?><div class="alert alert-danger"><?= e($error) ?></div><?php endif; ?><form method="post" class="card card-body mb-4"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">From</label><input class="form-control" type="date" name="from_date" required></div><div class="col-md-6"><label class="form-label">To</label><input class="form-control" type="date" name="to_date" required></div><div class="col-12"><label class="form-label">Reason</label><textarea class="form-control" name="reason" required></textarea></div><div><button class="btn btn-primary">Submit request</button></div></div></form><div class="card card-body"><h2 class="h5">My requests</h2><table class="table"><thead><tr><th>Dates</th><th>Reason</th><th>Status</th></tr></thead><tbody><?php foreach ($requests as $request): ?><tr><td><?= e($request['from_date'] . ' to ' . $request['to_date']) ?></td><td><?= e($request['reason']) ?></td><td><?= e(ucfirst($request['status'])) ?></td></tr><?php endforeach; ?></tbody></table></div></main></body></html>
