<?php
declare(strict_types=1);
require_once __DIR__ . '/access.php';
require_role('client');
$pdo = db(); $userId = (int) $_SESSION['user']['id'];
$clientStmt = $pdo->prepare('SELECT id FROM clients WHERE user_id = ? AND active = 1 LIMIT 1'); $clientStmt->execute([$userId]); $clientId = (int) $clientStmt->fetchColumn();
$allowed = ['all', 'Paid', 'Pending', 'Overdue']; $filter = in_array($_GET['status'] ?? 'all', $allowed, true) ? (string) ($_GET['status'] ?? 'all') : 'all';
$rows = []; $totalDue = 0;
if ($clientId) {
    $totalStmt = $pdo->prepare('SELECT COALESCE(SUM(pending_amount), 0) FROM client_payments WHERE client_id = ?'); $totalStmt->execute([$clientId]); $totalDue = (float) $totalStmt->fetchColumn();
    $sql = 'SELECT * FROM client_payments WHERE client_id = ?'; $params = [$clientId];
    if ($filter === 'Paid') { $sql .= " AND payment_status = 'Paid'"; }
    elseif ($filter === 'Pending') { $sql .= " AND payment_status IN ('Pending', 'Partially Paid')"; }
    elseif ($filter === 'Overdue') { $sql .= " AND (payment_status = 'Overdue' OR (pending_amount > 0 AND due_date < CURDATE()))"; }
    $sql .= ' ORDER BY invoice_date DESC'; $stmt = $pdo->prepare($sql); $stmt->execute($params); $rows = $stmt->fetchAll();
}
function invoice_inr(float|int|string $amount): string { return '₹' . number_format((float) $amount, 2); }
echo '<style>.invoice-filters{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:18px}.invoice-filters a{display:inline-flex;align-items:center;border:1px solid #6366f1;border-radius:8px;padding:8px 13px;color:#6366f1;background:#fff;text-decoration:none;font-size:13px;font-weight:600}.invoice-filters a.active{background:#6366f1;color:#fff}.saas-card .d-flex.flex-wrap.gap-2{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:18px}.saas-card .d-flex.flex-wrap.gap-2 a.btn{display:inline-flex;align-items:center;border:1px solid #6366f1;border-radius:8px;padding:8px 13px;color:#6366f1;background:#fff;text-decoration:none;font-size:13px;font-weight:600}.saas-card .d-flex.flex-wrap.gap-2 a.btn.btn-primary{background:#6366f1;color:#fff}.saas-topbar>a{display:inline-flex;align-items:center;border:1px solid #6366f1;border-radius:8px;padding:8px 13px;color:#6366f1;background:#fff;text-decoration:none;font-size:13px;font-weight:600}</style>';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>My Invoices</title><link rel="stylesheet" href="assets/css/saas.css"><script src="assets/js/session-timeout.js" defer></script></head><body class="saas-body"><div class="saas-shell"><aside class="saas-sidebar"><div class="brand"><span>MT</span> Mega Techzy</div><div class="nav-label">Workspace</div><a class="saas-nav" href="client_dashboard.php">▦ <span>Overview</span></a><a class="saas-nav" href="client_content_plan.php">◷ <span>Content plan</span></a><a class="saas-nav" href="content_archive.php">▤ <span>Archive</span></a><a class="saas-nav" href="view_client_profile.php?client_id=<?= $clientId ?>">♙ <span>My profile</span></a><a class="saas-nav active" href="my_invoices.php">▧ <span>Invoices</span></a><div class="nav-label">Account</div><a class="saas-nav" href="logout.php">↪ <span>Log out</span></a></aside><main class="saas-main"><header class="saas-topbar"><div><h1 class="saas-title">My invoices</h1><div class="saas-subtitle">Your linked client billing records only.</div></div><a href="client_dashboard.php">Dashboard</a></header><section class="kpi-grid"><div class="kpi-card expense"><div class="kpi-icon red">₹</div><div class="kpi-label">Total due</div><div class="kpi-value"><?= invoice_inr($totalDue) ?></div><div class="trend muted">Outstanding amount</div></div></section><section class="saas-card"><div class="d-flex flex-wrap gap-2 mb-3"><?php foreach (['all' => 'All', 'Paid' => 'Paid', 'Pending' => 'Pending', 'Overdue' => 'Overdue'] as $key => $label): ?><a class="btn <?= $filter === $key ? 'btn-primary' : 'btn-outline-primary' ?>" href="my_invoices.php?status=<?= e($key) ?>"><?= e($label) ?></a><?php endforeach; ?></div><div style="overflow:auto"><table class="saas-table"><thead><tr><th>Invoice</th><th>Date</th><th>Due</th><th>Amount</th><th>Pending</th><th>Status</th><th>PDF</th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="7" class="text-center text-muted" style="padding:28px">No invoices found.</td></tr><?php else: foreach ($rows as $row): $overdue = (float) $row['pending_amount'] > 0 && $row['due_date'] < date('Y-m-d'); ?><tr><td><?= e($row['invoice_number']) ?></td><td><?= e($row['invoice_date']) ?></td><td class="<?= $overdue ? 'text-danger' : '' ?>"><?= e($row['due_date']) ?><?= $overdue ? ' · Overdue' : '' ?></td><td><?= invoice_inr($row['invoice_amount']) ?></td><td><?= invoice_inr($row['pending_amount']) ?></td><td><span class="status-pill status-<?= $overdue ? 'overdue' : strtolower($row['payment_status']) ?>"><?= e($overdue ? 'Overdue' : $row['payment_status']) ?></span></td><td><a class="btn-outline-indigo" href="download_invoice.php?invoice_number=<?= urlencode($row['invoice_number']) ?>">Download</a></td></tr><?php endforeach; endif; ?></tbody></table></div></section></main></div></body></html>
