<?php
declare(strict_types=1);
define('SAAS_NO_GLOBAL_NAV', true);
require_once __DIR__ . '/finance.php';
require_finance_admin();
$pdo=db();
$month=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['month']??$_POST['month']??''))?(string)($_GET['month']??$_POST['month']):date('Y-m');
$from=$month.'-01'; $to=date('Y-m-d',strtotime($from.' +1 month')); $message=null;
function payroll_setting(PDO $pdo,string $key,string $fallback=''):string{try{$s=$pdo->prepare('SELECT setting_value FROM settings WHERE setting_key=?');$s->execute([$key]);$v=$s->fetchColumn();return $v===false?$fallback:(string)$v;}catch(Throwable){return $fallback;}}
function payroll_working_days(PDO $pdo,string $from,string $to):int{$holidays=json_decode(payroll_setting($pdo,'holidays','[]'),true);$holidays=is_array($holidays)?array_fill_keys(array_map('strval',$holidays),true):[];$count=0;for($date=new DateTimeImmutable($from);$date->format('Y-m-d')<$to;$date=$date->modify('+1 day')){if((int)$date->format('N')<6&&!isset($holidays[$date->format('Y-m-d')]))$count++;}return $count;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();if(($_POST['action']??'generate')==='pay'){$pdo->prepare("UPDATE salary_payroll SET payment_status='Paid',payment_date=CURDATE() WHERE id=?")->execute([(int)$_POST['id']]);$message='Payroll marked paid.';}else{$working=payroll_working_days($pdo,$from,$to);$employees=$pdo->query("SELECT u.id,COALESCE(s.monthly_salary,0) salary,COALESCE(s.fixed_allowance,0) allowance,COALESCE(s.deduction,0) deduction FROM users u LEFT JOIN staff_master s ON s.employee_id=u.id WHERE u.role='employee' AND u.active=1")->fetchAll();$attendance=$pdo->prepare("SELECT SUM(status='present') present,SUM(status='half_day') half_days,SUM(status='paid_leave') paid_leaves,SUM(status='absent') absent FROM attendance WHERE employee_id=? AND date>=? AND date<?");$save=$pdo->prepare('INSERT INTO salary_payroll(month_year,employee_id,working_days,present_days,half_days,paid_leaves,absent_days,payable_days,basic_salary_payable,allowance,deduction,net_salary) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE working_days=VALUES(working_days),present_days=VALUES(present_days),half_days=VALUES(half_days),paid_leaves=VALUES(paid_leaves),absent_days=VALUES(absent_days),payable_days=VALUES(payable_days),basic_salary_payable=VALUES(basic_salary_payable),allowance=VALUES(allowance),deduction=VALUES(deduction),net_salary=VALUES(net_salary)');foreach($employees as $employee){$attendance->execute([$employee['id'],$from,$to]);$row=$attendance->fetch()?:[];$present=(float)($row['present']??0);$half=(float)($row['half_days']??0);$leave=(float)($row['paid_leaves']??0);$absent=(float)($row['absent']??0);$payable=$present+$leave+($half*.5);$basic=$working?((float)$employee['salary']/$working)*$payable:0;$save->execute([$month,$employee['id'],$working,$present,$half,$leave,$absent,$payable,$basic,$employee['allowance'],$employee['deduction'],$basic+(float)$employee['allowance']-(float)$employee['deduction']]);}$message="Payroll generated for {$month} using {$working} working days.";}}
$stmt=$pdo->prepare('SELECT p.*,u.name FROM salary_payroll p INNER JOIN users u ON u.id=p.employee_id WHERE p.month_year=? ORDER BY u.name');$stmt->execute([$month]);$rows=$stmt->fetchAll();function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payroll</title><link rel="stylesheet" href="assets/css/saas.css"></head><body class="saas-body"><div class="saas-shell"><aside class="saas-sidebar"><div class="brand"><span>MT</span> Mega Techzy</div><div class="nav-label">Workspace</div><a class="saas-nav" href="admin_dashboard.php">▦ <span>Overview</span></a><a class="saas-nav" href="finance_dashboard.php">◈ <span>Finance</span></a><a class="saas-nav" href="manage_clients.php">♙ <span>Clients</span></a><a class="saas-nav" href="manage_users.php">♟ <span>Users</span></a><div class="nav-label">Operations</div><a class="saas-nav" href="admin_attendance.php">◷ <span>Attendance</span></a><a class="saas-nav" href="staff_master.php">♙ <span>Staff Master</span></a><a class="saas-nav active" href="payroll.php">▤ <span>Payroll</span></a><a class="saas-nav" href="invoices.php">▧ <span>Invoices</span></a><a class="saas-nav" href="expenses.php">▣ <span>Expenses</span></a><a class="saas-nav" href="cashflow.php">↗ <span>Cash flow</span></a><div class="nav-label">Account</div><a class="saas-nav" href="logout.php">↪ <span>Log out</span></a></aside><main class="saas-main"><h1 class="saas-title">Payroll</h1><?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><form method="post" class="saas-card"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="generate"><input type="month" name="month" value="<?=e($month)?>"><button class="btn-indigo">Generate / Recalculate</button></form><section class="saas-card"><table class="saas-table"><thead><tr><th>Employee</th><th>Working days</th><th>Payable days</th><th>Net salary</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=e($row['name'])?></td><td><?=e((string)$row['working_days'])?></td><td><?=e((string)$row['payable_days'])?></td><td><?=inr($row['net_salary'])?></td><td><?=e($row['payment_status'])?></td><td><?php if($row['payment_status']==='Pending'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="pay"><input type="hidden" name="id" value="<?=$row['id']?>"><button class="btn-outline-indigo">Mark paid</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></section></main></div></body></html>
