<?php
declare(strict_types=1);
require_once __DIR__ . '/access.php'; require_login();
$isAdmin = $_SESSION['user']['role'] === 'admin';
$month = preg_match('/^\d{4}-\d{2}$/', (string) ($_GET['month'] ?? '')) ? (string) $_GET['month'] : date('Y-m');
$from = $month . '-01'; $to = date('Y-m-d', strtotime($from . ' +1 month'));
$userStmt = $isAdmin ? db()->query("SELECT id, name FROM users WHERE role = 'employee' ORDER BY name") : db()->prepare("SELECT id, name FROM users WHERE id = ? AND role = 'employee'");
if (!$isAdmin) { $userStmt->execute([$_SESSION['user']['id']]); }
$employees = $userStmt->fetchAll(); $rows = [];
foreach ($employees as $employee) { $id = (int) $employee['id']; $stmt = db()->prepare('SELECT COUNT(*) total, SUM(status = \'present\') present FROM attendance WHERE employee_id = ? AND date >= ? AND date < ?'); $stmt->execute([$id, $from, $to]); $attendance = $stmt->fetch(); $stmt = db()->prepare('SELECT COUNT(*) assigned, SUM(status = \'completed\') completed FROM tasks WHERE assigned_to = ? AND created_at >= ? AND created_at < ?'); $stmt->execute([$id, $from, $to]); $tasks = $stmt->fetch(); $stmt = db()->prepare("SELECT COUNT(*) uploads, SUM(status = 'approved') approved, SUM(status = 'changes_requested') changes_requested, AVG(CASE WHEN status = 'approved' THEN TIMESTAMPDIFF(HOUR, created_at, updated_at) END) avg_turnaround FROM content WHERE employee_id = ? AND created_at >= ? AND created_at < ?"); $stmt->execute([$id, $from, $to]); $content = $stmt->fetch(); $reviewed = (int) $content['approved'] + (int) $content['changes_requested']; $rows[] = ['name' => $employee['name'], 'attendance' => $attendance['total'] ? round(((int) $attendance['present'] / (int) $attendance['total']) * 100, 1) : 0, 'assigned' => (int) $tasks['assigned'], 'completed' => (int) $tasks['completed'], 'uploads' => (int) $content['uploads'], 'approval_rate' => $reviewed ? round(((int) $content['approved'] / $reviewed) * 100, 1) : 0, 'turnaround' => $content['avg_turnaround'] !== null ? round((float) $content['avg_turnaround'], 1) : 0]; }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Performance Report</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-4"><div class="d-flex justify-content-between"><h1 class="h3">Performance Report</h1><a href="<?= $isAdmin ? 'admin_dashboard.php' : 'employee_dashboard.php' ?>">Dashboard</a></div><form class="mb-3"><label class="form-label">Month</label><input class="form-control" style="max-width:220px" type="month" name="month" value="<?= e($month) ?>"><button class="btn btn-primary mt-2">View report</button></form><div class="card card-body"><div class="table-responsive"><table class="table"><thead><tr><th>Employee</th><th>Attendance</th><th>Tasks</th><th>Uploads</th><th>Approval rate</th><th>Avg turnaround</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><?= e($row['name']) ?></td><td><?= $row['attendance'] ?>%</td><td><?= $row['completed'] ?> / <?= $row['assigned'] ?></td><td><?= $row['uploads'] ?></td><td><?= $row['approval_rate'] ?>%</td><td><?= $row['turnaround'] ?> hours</td></tr><?php endforeach; ?></tbody></table></div></div></main></body></html>
